Update current_branch.yaml

diff --git a/.github/workflows/current_branch.yaml b/.github/workflows/current_branch.yaml
--- a/.github/workflows/current_branch.yaml
+++ b/.github/workflows/current_branch.yaml
@@ -96,31 +96,32 @@ jobs:
                 ;;
             esac
       
+            echo "pipelineType: $pipelineType"
             echo "pipelineType=$pipelineType" >> $GITHUB_OUTPUT
           # done < <(echo "$PIPELINE" | grep -oP 'type: \K\w+')
           done < <(echo "$PIPELINE" | yq eval '.deployment.type' -)
             
 
-      - name: Validate
-        id: validate
-        env:
-          pipelinetype: ${{ steps.set-pipeline.outputs.pipelineType }}
-          PIPELINE: ${{ needs.main.outputs.pipelineYaml }}
-        run: |
-          if [ "${PIPELINE_TYPE}" = "K8sClassic" ] || [ "${PIPELINE_TYPE}" = "mobility" ]; then
-            echo "Checking for containerBuild in $PIPELINE"
+      # - name: Validate
+      #   id: validate
+      #   env:
+      #     pipelinetype: ${{ steps.set-pipeline.outputs.pipelineType }}
+      #     PIPELINE: ${{ needs.main.outputs.pipelineYaml }}
+      #   run: |
+      #     if [ "${PIPELINE_TYPE}" = "K8sClassic" ] || [ "${PIPELINE_TYPE}" = "mobility" ]; then
+      #       echo "Checking for containerBuild in $PIPELINE"
           
-            # Print the content of PIPELINE for debugging
-            echo "PIPELINE content:"
-            cat "$PIPELINE"
-            # Check if containerBuild exists
-            if yq eval '.containerBuild' "$PIPELINE"; then
-              echo "containerBuild is present"
-            else
-              echo "Configuration error: missing containerBuild" >&2
-              exit 1
-            fi
-          fi
+      #       # Print the content of PIPELINE for debugging
+      #       echo "PIPELINE content:"
+      #       cat "$PIPELINE"
+      #       # Check if containerBuild exists
+      #       if yq eval '.containerBuild' "$PIPELINE"; then
+      #         echo "containerBuild is present"
+      #       else
+      #         echo "Configuration error: missing containerBuild" >&2
+      #         exit 1
+      #       fi
+      #     fi
 
 
           # if [ "${PIPELINE_TYPE}" = "K8sClassic" ] || [ "${PIPELINE_TYPE}" = "mobility" ]; then
