Update current_branch.yaml

diff --git a/.github/workflows/current_branch.yaml b/.github/workflows/current_branch.yaml
--- a/.github/workflows/current_branch.yaml
+++ b/.github/workflows/current_branch.yaml
@@ -109,18 +109,29 @@ jobs:
         run: |
           if [ "${PIPELINE_TYPE}" = "K8sClassic" ] || [ "${PIPELINE_TYPE}" = "mobility" ]; then
             # Check if containerBuild exists
-            if ! yq eval '.containerBuild' "$PIPELINE" >/dev/null 2>&1; then
+            if yq eval '.containerBuild' "$PIPELINE" >/dev/null 2>&1; then
+              echo "containerBuild is present"
+            else
               echo "Configuration error: missing containerBuild" >&2
               exit 1
             fi
-
-            # Check if imageName under containerBuild exists
-            if ! yq eval '.containerBuild.imageName' path/to/your/file.yaml >/dev/null 2>&1; then
-              echo "Configuration error: missing containerBuild.imageName" >&2
-              exit 1
-            fi
-            echo "YAML validation successful"
           fi
+
+
+          # if [ "${PIPELINE_TYPE}" = "K8sClassic" ] || [ "${PIPELINE_TYPE}" = "mobility" ]; then
+          #   # Check if containerBuild exists
+          #   if ! yq eval '.containerBuild' "$PIPELINE" >/dev/null 2>&1; then
+          #     echo "Configuration error: missing containerBuild" >&2
+          #     exit 1
+          #   fi
+
+          #   # Check if imageName under containerBuild exists
+          #   if ! yq eval '.containerBuild.imageName' path/to/your/file.yaml >/dev/null 2>&1; then
+          #     echo "Configuration error: missing containerBuild.imageName" >&2
+          #     exit 1
+          #   fi
+          #   echo "YAML validation successful"
+          # fi
               
 
           #   echo "YAML validation successful"
