Update current_branch.yaml

diff --git a/.github/workflows/current_branch.yaml b/.github/workflows/current_branch.yaml
--- a/.github/workflows/current_branch.yaml
+++ b/.github/workflows/current_branch.yaml
@@ -110,17 +110,28 @@ jobs:
         run: |
           if [ "${pipelinetype}" = "K8sClassic" ] || [ "${pipelinetype}" = "mobility" ]; then
             echo "Checking for containerBuild in $PIPELINE"
-          
+            
             # Print the content of PIPELINE for debugging
             echo "PIPELINE content:"
             echo "$PIPELINE"
-            # Check if containerBuild exists
-            if yq eval '.containerBuild' "$PIPELINE"; then
+      
+            # Check if .containerBuild exists
+            if yq e '.containerBuild' "$PIPELINE" >/dev/null 2>&1; then
               echo "containerBuild is present"
             else
               echo "Configuration error: missing containerBuild" >&2
               exit 1
             fi
+      
+            # Check if .containerBuild.imageName exists
+            if yq e '.containerBuild.imageName' "$PIPELINE" >/dev/null 2>&1; then
+              echo "imageName is present under containerBuild"
+            else
+              echo "Configuration error: missing containerBuild.imageName" >&2
+              exit 1
+            fi
+      
+            echo "YAML validation successful"
           fi
 
 
