Update current_branch.yaml

diff --git a/.github/workflows/current_branch.yaml b/.github/workflows/current_branch.yaml
--- a/.github/workflows/current_branch.yaml
+++ b/.github/workflows/current_branch.yaml
@@ -305,13 +305,17 @@ jobs:
             branch=$(echo "$PIPELINE" | yq eval ".environments.$key.branch" -)
             echo "Environment: $key, Branch in YAML: $branch, Current Branch: $CURRENT_BRANCH"
             # Check if the current branch matches the environment branch
-            if [ "${branch}" != "null" ] && [[ "${CURRENT_BRANCH}" =~ ^${branch}$ ]]; then
-            # if [ "${CURRENT_BRANCH}" = "${branch}" ]; then
+            if [ "${branch}" != "null" ] && [[ "${CURRENT_BRANCH}" == ${branch%%/*}* ]]; then
               echo "Current branch matches for environment: $key"
+              found_match=true
+            else
+              # Exit the job early if found_match is not true
+              echo "No match found. Exiting the job."
+              exit 1  # Use a non-zero status code to indicate failure
             fi
-          done 
 
       - name: fetch image
+        if: steps.validate-branch.outputs.found_match == 'true'
         id: image
         env:
           CURRENT_BRANCH: ${{ needs.main.outputs.branch }}
