Update current_branch.yaml

diff --git a/.github/workflows/current_branch.yaml b/.github/workflows/current_branch.yaml
--- a/.github/workflows/current_branch.yaml
+++ b/.github/workflows/current_branch.yaml
@@ -299,20 +299,27 @@ jobs:
           PIPELINE: ${{ needs.main.outputs.pipelineYaml }}
         run: |
           echo "Validating the branch for environments:"
+          # Set a flag to track if any match is found
+          found_match=false
+          
           # Loop through environments
           keys=$(echo "$PIPELINE" | yq eval '.environments | keys | .[]' -)
           for key in $keys; do
             branch=$(echo "$PIPELINE" | yq eval ".environments.$key.branch" -)
             echo "Environment: $key, Branch in YAML: $branch, Current Branch: $CURRENT_BRANCH"
+            
             # Check if the current branch matches the environment branch
             if [ "${branch}" != "null" ] && [[ "${CURRENT_BRANCH}" == ${branch%%/*}* ]]; then
               echo "Current branch matches for environment: $key"
-            else
-              # Exit the job early if found_match is not true
-              echo "No match found. Exiting the job."
-              exit 1  # Use a non-zero status code to indicate failure
+              found_match=true
             fi
-          done 
+          done
+          
+          # Exit the job if no match is found
+          if [ "$found_match" = false ]; then
+            echo "No match found. Exiting the job."
+            exit 1  # Use a non-zero status code to indicate failure
+          fi
 
       # - name: Validate the branch
       #   id: validate-branch
