Update current_branch.yaml

diff --git a/.github/workflows/current_branch.yaml b/.github/workflows/current_branch.yaml
--- a/.github/workflows/current_branch.yaml
+++ b/.github/workflows/current_branch.yaml
@@ -130,7 +130,23 @@ jobs:
               echo "Configuration error: missing containerBuild" >&2
               exit 1
             fi
-      
+
+            if [ "$(echo "$PIPELINE" | yq eval '.build' -)" != "null" ]; then
+              if [ "$(echo "$PIPELINE" | yq eval '.build.image' -)" != "null" ] && [ "$(echo "$PIPELINE" | yq eval '.build.steps' -)" != "null" ]; then
+                echo "build.image and build.steps are present"
+              else
+                echo "Configuration error: missing build.image or build.steps" >&2
+                exit 1
+              fi
+            fi
+
+
+            echo "#########TESTING############"
+            echo "Checking for containerBuild in $PIPELINE"
+            
+            # Print the content of PIPELINE for debugging
+            echo "PIPELINE content:"
+            
             echo "YAML validation successful"
           fi
 
