Update current_branch.yaml

diff --git a/.github/workflows/current_branch.yaml b/.github/workflows/current_branch.yaml
--- a/.github/workflows/current_branch.yaml
+++ b/.github/workflows/current_branch.yaml
@@ -88,6 +88,9 @@ jobs:
               K8sClassic)
                 pipelineType="K8sClassic"
                 ;;
+              S3)
+                pipelineType="S3"
+                ;;
               helm)
                 pipelineType="helm"
                 ;;
@@ -102,13 +105,14 @@ jobs:
           done < <(echo "$PIPELINE" | yq eval '.deployment.type' -)
             
 
-      - name: Validate
-        id: validate
+      - name: Validate K8sClassic and mobility
+        if: ${{ [ ${pipelinetype}" = "K8sClassic" ] || [ "${pipelinetype}" = "mobility" ] }}
+        id: validate-K8sClassic
         env:
           pipelinetype: ${{ steps.set-pipeline.outputs.pipelineType }}
           PIPELINE: ${{ needs.main.outputs.pipelineYaml }}
         run: |
-          if [ "${pipelinetype}" = "K8sClassic" ] || [ "${pipelinetype}" = "mobility" ]; then
+          # if [ "${pipelinetype}" = "K8sClassic" ] || [ "${pipelinetype}" = "mobility" ]; then
             echo "Checking for containerBuild in pipeline.yaml"     
             # Check if .containerBuild exists
             if [ "$(echo "$PIPELINE" | yq eval '.containerBuild' -)" != "null" ] && [ "$(echo "$PIPELINE" | yq eval '.containerBuild.imageName' -)" != "null" ]; then
@@ -152,7 +156,7 @@ jobs:
                 fi
               fi
             done
-          fi
+            
             echo "Checking for deployment in pipeline.yaml"     
             # Check if .deployment exists
             if [ "$(echo "$PIPELINE" | yq eval '.deployment.name' -)" != "null" ] && [ "$(echo "$PIPELINE" | yq eval '.deployment.namespace' -)" != "null" ] && [ "$(echo "$PIPELINE" | yq eval '.deployment.containerPort' -)" != "null" ]&& [ "$(echo "$PIPELINE" | yq eval '.deployment.replicas' -)" != "null" ]&& [ "$(echo "$PIPELINE" | yq eval '.deployment.healthCheckPath' -)" != "null" ] && [ "$(echo "$PIPELINE" | yq eval '.deployment.healthCheckPort' -)" != "null" ] && [ "$(echo "$PIPELINE" | yq eval '.deployment.cpu' -)" != "null" ] && [ "$(echo "$PIPELINE" | yq eval '.deployment.memory' -)" != "null" ] ; then
@@ -173,30 +177,119 @@ jobs:
               fi
             fi
 
+      - name: Validate Helm
+        if: ${{ [ ${pipelinetype}" = "helm" ] }}
+        id: validate-helm
+        env:
+          pipelinetype: ${{ steps.set-pipeline.outputs.pipelineType }}
+          PIPELINE: ${{ needs.main.outputs.pipelineYaml }}
+        run: |
+          # if [ "${pipelinetype}" = "K8sClassic" ] || [ "${pipelinetype}" = "mobility" ]; then
+            echo "Checking for containerBuild in pipeline.yaml"     
+            # Check if .containerBuild exists
+            if [ "$(echo "$PIPELINE" | yq eval '.containerBuild' -)" != "null" ] && [ "$(echo "$PIPELINE" | yq eval '.containerBuild.imageName' -)" != "null" ]; then
+              echo "containerBuild and imageName is present"
+            else
+              echo "Configuration error: missing containerBuild and imageName" >&2
+              exit 1
+            fi
 
-          #   echo "#########TESTING############"
-          #   echo "Checking for containerBuild in pipeline"
-            
-          #   # Print the content of PIPELINE for debugging
-            
-          #   echo "YAML validation successful"
-          # fi
+            echo "Checking for build in pipeline.yaml" 
+            # Check if .build exists
+            if [ "$(echo "$PIPELINE" | yq eval '.build' -)" != "null" ]; then
+              if [ "$(echo "$PIPELINE" | yq eval '.build.image' -)" != "null" ] && [ "$(echo "$PIPELINE" | yq eval '.build.steps' -)" != "null" ]; then
+                echo "build.image and build.steps are present"
+              else
+                echo "Configuration error: missing build.image or build.steps" >&2
+                exit 1
+              fi
+            fi
 
+            echo "Checking for environment in pipeline.yaml" 
+            # Checking for environment cluster
+            keys=$(echo "$PIPELINE" | yq eval '.environments | keys | .[]' -)
+            for key in $keys; do
+              if [ "$(echo "$PIPELINE" | yq eval '.environments."'"${key}"'".cluster' -)" != "null" ]; then
+                echo "envirnment cluster is present for $key"
+              else
+                echo "Configuration error: missing envirnment cluster for $key" >&2
+              exit 1
+              fi
+            done
+     
+            # Checking for environment promotion
+            for key in $keys; do
+              if [ "$(echo "$PIPELINE" | yq eval '.environments."'"${key}"'".promotion' -)" != "null" ]; then
+                if [ "$(echo "$PIPELINE" | yq eval '.environments."'"${key}"'".promotion.to' -)" != "null" ]; then
+                  echo "Validation successful for $key"
+                else
+                  echo "Configuration error: missing promotion.to for $key" >&2
+                  exit 1
+                fi
+              fi
+            done
 
-          # if [ "${PIPELINE_TYPE}" = "K8sClassic" ] || [ "${PIPELINE_TYPE}" = "mobility" ]; then
-          #   # Check if containerBuild exists
-          #   if ! yq eval '.containerBuild' "$PIPELINE" >/dev/null 2>&1; then
-          #     echo "Configuration error: missing containerBuild" >&2
-          #     exit 1
-          #   fi
+            echo "Checking for deployment in pipeline.yaml"     
+            # Check if .deployment exists
+            if [ "$(echo "$PIPELINE" | yq eval '.deployment.name' -)" != "null" ] && [ "$(echo "$PIPELINE" | yq eval '.deployment.namespace' -)" != "null" ] && [ "$(echo "$PIPELINE" | yq eval '.deployment.chartName' -)" != "null" ]; then
+              echo "deployment, name, namespace, chartName is present"
+            else
+              echo "Configuration error: missing Deployment/name/namespace/chartName " >&2
+              exit 1
+            fi
 
-          #   # Check if imageName under containerBuild exists
-          #   if ! yq eval '.containerBuild.imageName' path/to/your/file.yaml >/dev/null 2>&1; then
-          #     echo "Configuration error: missing containerBuild.imageName" >&2
-          #     exit 1
-          #   fi
-          #   echo "YAML validation successful"
-          # fi
+      - name: Validate S3
+        if: ${{ [ ${pipelinetype}" = "K8sClassic" ] || [ "${pipelinetype}" = "mobility" ] }}
+        id: validate-S3
+        env:
+          pipelinetype: ${{ steps.set-pipeline.outputs.pipelineType }}
+          PIPELINE: ${{ needs.main.outputs.pipelineYaml }}
+        run: |
+          # if [ "${pipelinetype}" = "K8sClassic" ] || [ "${pipelinetype}" = "mobility" ]; then
+            echo "Checking for containerBuild in pipeline.yaml"     
+            # Check if .containerBuild exists
+            if [ "$(echo "$PIPELINE" | yq eval '.containerBuild' -)" != "null" ] && [ "$(echo "$PIPELINE" | yq eval '.containerBuild.imageName' -)" != "null" ]; then
+              echo "containerBuild and imageName is present"
+            else
+              echo "Configuration error: missing containerBuild and imageName" >&2
+              exit 1
+            fi
+
+            echo "Checking for build in pipeline.yaml" 
+            # Check if .build exists
+            if [ "$(echo "$PIPELINE" | yq eval '.build' -)" != "null" ]; then
+              if [ "$(echo "$PIPELINE" | yq eval '.build.image' -)" != "null" ] && [ "$(echo "$PIPELINE" | yq eval '.build.steps' -)" != "null" ]; then
+                echo "build.image and build.steps are present"
+              else
+                echo "Configuration error: missing build.image or build.steps" >&2
+                exit 1
+              fi
+            fi
+
+            echo "Checking for environment in pipeline.yaml" 
+            # Checking for environment cluster
+            keys=$(echo "$PIPELINE" | yq eval '.environments | keys | .[]' -)
+            # Checking for environment promotion
+            for key in $keys; do
+              if [ "$(echo "$PIPELINE" | yq eval '.environments."'"${key}"'".promotion' -)" != "null" ]; then
+                if [ "$(echo "$PIPELINE" | yq eval '.environments."'"${key}"'".promotion.to' -)" != "null" ]; then
+                  echo "Validation successful for $key"
+                else
+                  echo "Configuration error: missing promotion.to or promotion.mergeTo for $key" >&2
+                  exit 1
+                fi
+              fi
+            done
+
+            echo "Checking for deployment in pipeline.yaml"     
+            # Check if .deployment exists
+            if [ "$(echo "$PIPELINE" | yq eval '.deployment.name' -)" != "null" ] ; then
+              echo "deployment, name is present"
+            else
+              echo "Configuration error: missing Deployment/name " >&2
+              exit 1
+            fi
+
               
 
           #   echo "YAML validation successful"
