Update current_branch.yaml

diff --git a/.github/workflows/current_branch.yaml b/.github/workflows/current_branch.yaml
--- a/.github/workflows/current_branch.yaml
+++ b/.github/workflows/current_branch.yaml
@@ -116,20 +116,20 @@ jobs:
             echo "$PIPELINE"
       
             # Check if .containerBuild exists
-            if [ "$(echo "$PIPELINE" | yq eval '.containerBuild.imageName' -)" != "null" ]; then
+            if [ "$(echo "$PIPELINE" | yq eval '.containerBuild' -)" != "null" ]; then
               echo "containerBuild is present"
             else
               echo "Configuration error: missing containerBuild" >&2
               exit 1
             fi
       
-            # # Check if .containerBuild.imageName exists
-            # if yq e '.containerBuild.imageName' "$PIPELINE" >/dev/null 2>&1; then
-            #   echo "imageName is present under containerBuild"
-            # else
-            #   echo "Configuration error: missing containerBuild.imageName" >&2
-            #   exit 1
-            # fi
+            # Check if .containerBuild.imageName exists
+            if [ "$(echo "$PIPELINE" | yq eval '.containerBuild.imageName' -)" != "null" ]; then
+              echo "containerBuild is present"
+            else
+              echo "Configuration error: missing containerBuild" >&2
+              exit 1
+            fi
       
             echo "YAML validation successful"
           fi
