Update promote.yaml

diff --git a/.github/workflows/promote.yaml b/.github/workflows/promote.yaml
--- a/.github/workflows/promote.yaml
+++ b/.github/workflows/promote.yaml
@@ -17,6 +17,14 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v2
 
+      - name: Extract branch name
+        shell: bash
+        run: |
+          branch_name="${GITHUB_REF#refs/heads/}"
+          echo "BRANCH=$branch_name" | tee -a $GITHUB_OUTPUT
+          echo "branch: $branch_name"
+        id: current_branch
+
       - name: Read Pipeline YAML
         id: read_yaml
         run: |
@@ -48,3 +56,44 @@ jobs:
           keys=$(echo "$PIPELINE" | yq eval '.environments | keys | .[0]' -)
           echo "keys: $keys"
         id: current_branch
+
+      - name: List the Environmets
+        shell: bash
+        id: env-list
+        env:
+          PIPELINE: ${{ needs.main.outputs.pipelineYaml }}
+          CURRENT_BRANCH: ${{ needs.main.outputs.branch }}
+        run: |
+          echo "current_branch: $current_branch"
+          echo "Validating the branch for environments:"
+          # Set a flag to track if any match is found
+          found_match=false
+          
+          # Loop through environments
+          keys=$(echo "$PIPELINE" | yq eval '.environments | keys | .[]' -)
+          for key in $keys; do
+            branch=$(echo "$PIPELINE" | yq eval ".environments.$key.branch" -)
+            echo "Environment: $key, Branch in YAML: $branch, Current Branch: $CURRENT_BRANCH"
+            
+            # Check if the current branch matches the environment branch
+            if [ "${branch}" != "null" ] && [[ "${CURRENT_BRANCH}" == ${branch%%/*}* ]]; then
+              echo "Current branch matches for environment: $key"
+              found_match=true
+              matched_envs+=($key)
+            fi
+          done
+          
+          # Exit the job if no match is found
+          if [ "$found_match" = false ]; then
+            echo "No match found. Exiting the job."
+            exit 1  # Use a non-zero status code to indicate failure
+          fi   
+    
+          # Extract the mergeTo and to values for each matched environment
+          for env in "${matched_envs[@]}"; do
+            mergeTo=$(echo "$PIPELINE" | yq eval ".environments.$env.promotion.mergeTo" -)
+            to=$(echo "$PIPELINE" | yq eval ".environments.$env.promotion.to" -)
+      
+            # Store or use the values as needed
+            echo "For environment $env - mergeTo: $mergeTo, to: $to"
+          done
